# Generated by Django 3.1.4 on 2020-12-27 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassMentor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='akhlagh',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='detailes',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='nomre',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='tadris',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
